package com.smile.studio.recipe.model.greendao;

import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

import com.google.gson.annotations.SerializedName;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PECIPE".
 */
@Entity
public class Pecipe implements Parcelable {

    @Id(autoincrement = true)
    private Long id;

    public static final Creator<Pecipe> CREATOR = new Creator<Pecipe>() {
        @Override
        public Pecipe createFromParcel(Parcel in) {
            return new Pecipe(in);
        }

        @Override
        public Pecipe[] newArray(int size) {
            return new Pecipe[size];
        }
    };
    @SerializedName("id")
    @Index(unique = true)
    private long pid;
    @SerializedName("title")
    private String title;
    @SerializedName("image")
    private String image;
    @SerializedName("description")
    private String description;
    @SerializedName("content")
    private String content;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Pecipe() {
    }

    public Pecipe(Long id) {
        this.id = id;
    }

    @Generated
    public Pecipe(Long id, long pid, String title, String image, String description, String content, Integer type) {
        this.id = id;
        this.pid = pid;
        this.title = title;
        this.image = image;
        this.description = description;
        this.content = content;
        this.type = type;
    }

    protected Pecipe(Parcel in) {
        if (in.readByte() == 0) {
            id = null;
        } else {
            id = in.readLong();
        }
        pid = in.readLong();
        title = in.readString();
        image = in.readString();
        description = in.readString();
        content = in.readString();
        if (in.readByte() == 0) {
            type = null;
        } else {
            type = in.readInt();
        }
    }

    @SerializedName("type")
    private Integer type;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPid() {
        return pid;
    }

    public void setPid(long pid) {
        this.pid = pid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        if (id == null) {
            dest.writeByte((byte) 0);
        } else {
            dest.writeByte((byte) 1);
            dest.writeLong(id);
        }
        dest.writeLong(pid);
        dest.writeString(title);
        dest.writeString(image);
        dest.writeString(description);
        dest.writeString(content);
        if (type == null) {
            dest.writeByte((byte) 0);
        } else {
            dest.writeByte((byte) 1);
            dest.writeInt(type);
        }
    }

    public void trace() {
        Log.e("Tag", "id: " + id + "\npid: " + pid + "\ntitle: " + title + "\ndescription: " + description + "\ncontent: " + content + "\ntype: " + type);
    }
    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
