package com.smile.studio.recipe.model.greendao;

import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

import com.google.gson.annotations.SerializedName;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TYPE".
 */
@Entity
public class Type implements Parcelable {

    @Id(autoincrement = true)
    private Long id;

    public static final Creator<Type> CREATOR = new Creator<Type>() {
        @Override
        public Type createFromParcel(Parcel in) {
            return new Type(in);
        }

        @Override
        public Type[] newArray(int size) {
            return new Type[size];
        }
    };
    @SerializedName("id")
    @Index(unique = true)
    private int pid;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Type() {
    }

    public Type(Long id) {
        this.id = id;
    }

    @Generated
    public Type(Long id, int pid, String title) {
        this.id = id;
        this.pid = pid;
        this.title = title;
    }

    @SerializedName("title")
    private String title;

    protected Type(Parcel in) {
        if (in.readByte() == 0) {
            id = null;
        } else {
            id = in.readLong();
        }
        pid = in.readInt();
        title = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPid() {
        return pid;
    }

    public void setPid(int pid) {
        this.pid = pid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        if (id == null) {
            dest.writeByte((byte) 0);
        } else {
            dest.writeByte((byte) 1);
            dest.writeLong(id);
        }
        dest.writeInt(pid);
        dest.writeString(title);
    }

    public void trace() {
        Log.e("Tag", "id: " + pid + "\ntitle: " + title);
    }
    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
